### ISSUE TITLE
Only live stream archive playing

### ISSUE THREAD

**Issue by Lucas-101** [bmlzootown/Hydravion#18]
When I try to play anything other then a live stream archive it just shows the error.

Error -1

Video cannot be played! There was an error in the HTTP response.  This could mean that malformed HTTP headers or an HTTP error code was returned.

**Comment by bmlzootown** [comment]
Which version of the channel are you currently running? The store channel is a bit behind, but both it and the beta channel work on my end.

If relogging doesn't fix the issue, you could try removing and then reinstalling the channel, or you could try the beta channel temporarily to see if that fixes the issue as it contains a few bug fixes/tweaks that the store channel does not: https://my.roku.com/account/add/TNCPHK5

Without being able to see logs or other output, there's no real sure-fire way to diagnose the issue at the moment. I've tried poking and prodding but I cannot seem to recreate the issue. The beta channel does have the ability to upload error logs if the user allows, but the output it provides is very lacking at the moment. I could make it more verbose, but I am still unable to push updates until the 2nd due to the blackout period.

**Comment by Lucas-101** [comment]
re logged same problem, reinstalled app same problem, installed beta works now!
