### ISSUE TITLE
Cannot select/enter channel

### ISSUE THREAD

**Issue by silicoid** [bmlzootown/Hydravion#21]
Model: Hisense 6Seriee-58
Hardware ID: G205X
Software Version: 11.5.0 build 4312-HC
Channel: Hydration 2.1 build 4
Channel: Linus Tech Tips 
Issue: Can login and see my channel subscriptions but nothing happens when I press Ok. Only * for the options works.

**Comment by bmlzootown** [comment]
This is due to recent temporary changes to video progress being set/queried on Floatplane's end. Unfortunately, I had assumed that such would always return a video's progress (which was an error on my end), so the channel gets stuck when the query fails and doesn't move on to the content screen.

That said, the beta channel (https://my.roku.com/account/add/HYDRTST) is currently working. I've also scheduled the fix to go live as early as possible for the main channel:
![image](https://user-images.githubusercontent.com/470706/227755540-6c841b83-810f-4c8f-99ac-91f9f815dd10.png)

**Comment by silicoid** [comment]
Works. Thank you!
