### ISSUE TITLE
Crashing to main menu.

### ISSUE THREAD

**Issue by MrPryor** [bmlzootown/Hydravion#8]

**Comment by bmlzootown** [comment]
Sorry, I'm just now seeing this. Can you describe the issue in a bit more detail? 

When/where exactly is it crashing -- when you go to play a video, video detail screen, video selection screen, sub screen, or is it just crashing as soon as you open? (And have you sideloaded the new source since the last commit, or are you using the private code via Roku?)

Thanks!

**Comment by bmlzootown** [comment]
I'm assuming _[this](https://linustechtips.com/main/topic/1052617-floatplane-unofficial-roku-channel/?do=findComment&comment=13131983)_ is related to the most recent reply on the LTT forum, so I'll link the post _[here](https://linustechtips.com/main/topic/1052617-floatplane-unofficial-roku-channel/?do=findComment&comment=13131983)_ for future reference.

**Comment by MrPryor** [comment]
Crashs to main menu as soon as you launch it. 
https://www.dropbox.com/s/qwfv8io00n791q7/20191222_062332.mp4?dl=0
Side load or Official: Official
Max resolution: 1080p
Model: 3900X – Roku Express
Software Version: 9.2.0 Build 4806-51

**Comment by bmlzootown** [comment]
I figured out what was causing the issue. The fix to a previous issue (they either switched to AES-128 recently, or the API call to grab the AES key previously didn't require proper cookies) meant that the video player couldn't be properly initialized until later. I've moved that bit of code, so all should be good. Already pushed an update.

If you're still having issues, by chance, feel free to reopen this issue.
